openapi: "3.0.0"
info:
  version: 0.1.0
  title: KINDER
  description: >-
      KINDER
  contact:
    name: Arun
    email: abclingam1@gmail.com
servers:
  - url: http://example.com
tags:
  - name: donors
    description: >-
      The API endpoints for the operations to be performed on the Donor level
  - name: Csrpartner
    description: >-
      The API endpoints for the operations to be performed on the Csrpartner level
  - name: Donee
    description: >-
      The API endpoints to be performed by the Donee
  - name: Donations
    description: >-
      The API endpoints to work with donation related information.
  - name: auth
    description: >-
      The API endpoints for the authentication of various user models.
paths:
   $ref: "./api/v1/spec.yaml"
